### PR TITLE
fix: show definition in bottom pane when dppn link is clicked

### LINKED ISSUE #280: Broken DPPN links
Green “n” DPPN links like the ones in picture aren’t working
6F3B70B2-0BF8-4D26-8A62-5708931D3EEF

### PR DESCRIPTION
**Pull request by rrogowski**
While debugging #280, I found two problems (both of which this PR addresses) that would prevent a DPPN definition from showing up:
- Clicking a DPPN link will not open the bottom pane if it is not already open
- Clicking a DPPN link doesn't work when the url path does not include an `analysis` parameter

Closes #280.

### CODE REVIEW

File: _dprhtml/js/dict_xml.js [hunk 1]
```diff
@@ -678,6 +678,10 @@ function displayDictData(data) {
     $(difbId).append(dataNode);
     $('#paliTextContent').scrollTop(0);
   }
+
+  if (DPR_PAL.isNavigationFeature()) {
+    __otherDialogsViewModel.showBottomPane(BottomPaneTabsViewModel.TabNumber.DICTIONARY);
```
Comment (rrogowski) [inline _dprhtml/js/dict_xml.js:683]: Originally, I used:
```javascript
__otherDialogsViewModel.showBottomPane(1);
```
but the value `1` is quite opaque, so I wanted to make it much easier for future maintainers to understand what this line is doing at a glance. Though it was not strictly necessary to create the [BottomPaneTabsViewModel.TabNumber](https://github.com/digitalpalireader/digitalpalireader/pull/330/files#diff-5f5df7e136837b52a20b4c9ce92df2008224a9b3d6aa4ab0a02e693ef1c7734aR4-R10) enum, I think the enhanced readability is worth the trade-off.

File: _dprhtml/js/dpr_pal.js [hunk 2]
```diff
@@ -125,7 +125,7 @@
       });
   }
 
-  DPR_PAL.getDifId = () => /analysis=[^&]/.test(window.location.href) ? 'difb-bottom' : 'difb';
+  DPR_PAL.getDifId = () => DPR_PAL.isNavigationFeature() ? 'difb-bottom' : 'difb';
```
Comment (rrogowski) [inline _dprhtml/js/dpr_pal.js:128]: It is possible to open the bottom pane via the `1` shortcut and click on a DPPN link before analyzing a word. As a result, checking the URL for the `analysis` parameter is insufficient to determine the correct `difId`.

File: _dprhtml/features/bottom-pane/init.js [hunk 3]
```diff
@@ -1,6 +1,14 @@
 'use strict';
 
 class BottomPaneTabsViewModel {
+  static TabNumber = {
```
Comment (rrogowski) [inline _dprhtml/features/bottom-pane/init.js:4]: Does this seem like a reasonable place for this enum to live?

**Review by parthopdas — COMMENTED** [review]
Please give me some more time - i am trying to dig out a video of exhaustive set of DPR scenarios - i'll send that to you so you can chose test out the relevant parts. 

this is essentially the characterization tests for all of DPR

this is also what i use right before prod deployment. once someone has done it a few times all of it take ~10 mins.

File: _dprhtml/js/dict_xml.js (hunk 1 above)
Comment (rrogowski) [reply _dprhtml/js/dict_xml.js:683]: @parthopdas Ah, I understand now, thank you! Yes, using DPR1_chrome_mod.DPRShowBottomPane() does work! I will make that change.

File: _dprhtml/features/bottom-pane/init.js (hunk 3 above)
Comment (rrogowski) [reply _dprhtml/features/bottom-pane/init.js:4]: Since we discussed the DPR1_chrome_mod API should be used instead, I'm going to remove this enum for now since it isn't being used. We can always reintroduce if we touch code that uses the lower-level showBottomPane API.

**Review by parthopdas — APPROVED** [review]
Please push this through once you've verified the relevant scenarios.
